name: TradingCards
main: media.xen.tradingcards.TradingCards
version: ${project.version}
softdepend: [Towny, MobArena, Vault, MythicMobs]
author: Xenoyia
api-version: "1.13"

commands:
  cards:
    description: All commands.
    usage: /cards
    permission: cards.cards
    permission-message: You don't have permission to do this!

permissions:
  cards.cards:
    description: All commands.
    default: true
  cards.reload:
    description: Reload.
    default: op
  cards.givecard:
    description: Give a specific card.
    default: op
  cards.giveshinycard:
    description: Give a specific shiny card.
    default: op
  cards.giverandomcard:
    description: Give a random card.
    default: op
  cards.giveaway:
    description: Give away cards.
    default: op
  cards.create:
    description: Create a card.
    default: op
  cards.giveboosterpack:
    description: Give a booster pack.
    default: op
  cards.decks.*:
    description: Deck permissions.
    default: op
  cards.getdeck:
    description: Get a deck.
    default: true
  cards.list:
    description: List all cards.
    default: true
  cards.buy:
    description: Buy cards or packs.
    default: true
  cards.sell:
    description: Sell the card you are holding.
    default: true
  cards.worth:
    description: Get the value of the card.
    default: true
  cards.toggle:
    description: Toggle cards.
    default: true
  cards.listpacks:
    description: Lists all booster packs.
    default: true
  cards.resolve:
    description: Resolve a players UUID.
    default: op
  cards.reward:
    description: Claim a reward for collecting a whole rarity.
    default: true
  cards.list.others:
    description: Show another players deck progress.
    default: true