name: TradingCards
main: net.tinetwork.tradingcards.tradingcardsplugin.TradingCards
version: ${project.version}
softdepend: [Vault]
authors: [Xenoyia, sarhatabaot, TreasureIslandMC]
api-version: "1.13"