name: TradingCards
main: net.tinetwork.tradingcards.tradingcardsplugin.TradingCards
version: ${project.version}
softdepend: [Vault,PlaceholderAPI, TreasuryAPI]
authors: [Xenoyia, sarhatabaot, TreasureIslandMC]
api-version: "1.18"
libraries:
  - org.slf4j:slf4j-api:${slf4j.api.version}
  - org.spongepowered:configurate-yaml:${configurate.version}
  - org.spongepowered:configurate-hocon:${configurate.version}
  - net.kyori:adventure-api:${adventure.version}
  - net.kyori:adventure-platform-bukkit:${adventure.bukkit.version}
  - org.mariadb.jdbc:mariadb-java-client:${mariadb.version}
  - com.zaxxer:HikariCP:${hikaricp.version}
  - org.jooq:jooq:${jooq.version}
  - org.jooq:jooq-meta:${jooq.version}
  - org.jooq:jooq-codegen:${jooq.version}
  - org.jooq:jooq-meta-extension:${jooq.version}
  - net.lingala.zip4j:zip4j:${zip4j.version}
  - org.flywaydb:flyway-mysql:${flyway.version}